name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or the branch you want to trigger this workflow on
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: dev06/act-demo  # Set your Docker image name here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker buildx build --load --tag dev06/act-demo:${{ github.run_number }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push dev06/act-demo:${{ github.run_number }}
    
    - name: Remove Docker image
      run: |
        docker rmi dev06/act-demo:${{ github.run_number }}
